<?php declare(strict_types = 1);
/**
 * User: Hannes
 * Date: 20.11.2017
 * Time: 18:41
 */

namespace App\Tests;

class TestCase extends \PHPUnit\Framework\TestCase
{
    /** @var  \App\SparkPlug\Application */
    protected $app;

    protected function setUp()
    {
        $this->app = require __DIR__.'/../bootstrap/app.php';
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
