<?php declare(strict_types = 1);

namespace App\Tests;

use App\SparkPlug\Routing\Router;

/**
 * User: Hannes
 * Date: 23.10.2017
 * Time: 15:09
 */
class RouterTest extends TestCase
{
    /** @var  Router */
    private $router;

    /**
     * @covers \App\SparkPlug\Routing\Router::get()
     * @covers \App\SparkPlug\Routing\Router::getRoutes()
     */
    public function testAddRoute()
    {
        $this->router->get('index', 'FakeController@method');
        $this->assertEquals(1, count($this->router->getRoutes()['GET']));
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->router = app()->make(Router::class, true);
    }
}
